language: rust

matrix:
  include:
    - name: Tests
      os: windows
      install:
        # Workaround for choco failing to install .NET 3.5.
        # See https://travis-ci.community/t/unable-to-install-wix-toolset/1071/4?u=slonopotamus
        - powershell Install-WindowsFeature Net-Framework-Core
        - cinst -y wixtoolset
      script:
        # Unfortunately, there is currently no way to refresh our environment variables, so we have to set WIX manually
        # See https://travis-ci.community/t/refreshenv-for-bash/3753
        - export WIX="C:/Program Files (x86)/WiX Toolset v3.11/"
        - cargo test --all-targets -- --test-threads=1

    - name: Rustfmt
      install: rustup component add rustfmt
      script: cargo fmt --all -- --check

    - name: Clippy
      install: rustup component add clippy
      script: cargo clippy --all-targets -- -D warnings
